#++++++++++++++++++++++++++++++++
#++++++++++++++SHL+++++++++++
#++++++++++++++++++++++++++++++++
python src/data_preprocess/trajectory_feature_calcuation.py --trjs_path ./data/SHL_extracted/trjs.npy --labels_path ./data/SHL_extracted/labels.npy --n_class 5 --save_dir ./data/SHL_features/

python src/main.py --output_dir experiments --comment "pretraining through imputation" --name SHL_pretrained --records_file Imputation_records.xls --data_class SHL --val_ratio 0.2 --epochs 40 --lr 0.001 --optimizer RAdam --batch_size 1200 --pos_encoding learnable --d_model 128

python src/main.py --output_dir experiments --comment "finetune for classification" --name SHL_finetuned --records_file Classification_records.xls --data_class SHL --val_ratio 0.1 --test_ratio 0.2 --epochs 100 --lr 0.001 --optimizer RAdam --batch_size 1200 --pos_encoding learnable --d_model 128 --load_model ./experiments/SHL_pretrained_2021-10-03_13-05-13_Q2l/checkpoints/model_best.pth --task classification --change_output --key_metric accuracy

python src/main.py --output_dir experiments --comment "finetune for classification" --name SHL_finetuned --records_file Classification_records.xls --data_class SHL --val_ratio 0.1 --test_ratio 0.2 --epochs 100 --lr 0.001 --optimizer RAdam --batch_size 1200 --pos_encoding learnable --d_model 128 --load_model experiments/SHL_pretrained_2021-10-08_00-40-16_Ylz/checkpoints/model_best.pth --task classification --change_output --key_metric accuracy

#----------------10.21------------------
python src/main.py --output_dir experiments --comment "pretraining through feat_imputation" --name SHL_feature_pretrained --task denoising --records_file Imputation_records.xls --data_class SHL_feature --val_ratio 0.2 --epochs 40 --lr 0.001 --optimizer RAdam --batch_size 1200 --pos_encoding learnable --d_model 128

python src/main.py --output_dir experiments --comment "pretraining through trj_imputation" --name SHL_trj_pretrained --records_file Imputation_records.xls --data_class SHL_trajectory --val_ratio 0.2 --epochs 40 --lr 0.001 --optimizer RAdam --batch_size 1200 --pos_encoding learnable --d_model 128 --normalization per_sample_std

#----------------10.25------------------
python src/main.py --output_dir experiments --comment "pretraining through feat_denoising" --name SHL_feature_pretrained --task denoising --records_file Denoising_records.xls --data_class SHL_feature --val_ratio 0.2 --epochs 40 --lr 0.001 --optimizer RAdam --batch_size 500 --pos_encoding learnable --d_model 128

python src/main.py --output_dir experiments --comment "pretraining through trj_imputation" --name SHL_trj_pretrained --records_file Imputation_records.xls --data_class SHL_trajectory --val_ratio 0.2 --epochs 40 --lr 0.001 --optimizer RAdam --batch_size 600 --pos_encoding learnable --d_model 128 --normalization per_sample_minmax

#----------------10.28------------------
python src/main.py --output_dir experiments --comment "pretraining through feat_denoising" --name SHL_feature_pretrained --task denoising --records_file Denoising_records.xls --data_class feature --data_name SHL --val_ratio 0.2 --epochs 200 --lr 0.001 --optimizer RAdam --batch_size 500 --pos_encoding learnable --d_model 128

python src/main.py --output_dir experiments --comment "pretraining through trj_imputation" --name SHL_trj_pretrained --task imputation --records_file Imputation_records.xls --data_class trajectory --data_name SHL --val_ratio 0.2 --epochs 200 --lr 0.001 --optimizer RAdam --batch_size 520 --pos_encoding learnable --d_model 128 --normalization per_sample_minmax

python src/main.py --output_dir experiments --comment "dual branch finetune for classification" --name SHL_dual_branch_finetuned --records_file Classification_records.xls  --data_class trajectory_with_feature --data_name SHL --val_ratio 0.1 --test_ratio 0.2 --epochs 300 --lr 0.001 --optimizer RAdam --batch_size 550 --pos_encoding learnable --d_model 128 --task dual_branch_classification --change_output --key_metric accuracy --imputation_model_hyperparams experiments/SHL_trj_pretrained_2021-10-30_21-54-44_HL1/imputation_model_hyperparams.json --denoising_model_hyperparams experiments/SHL_feature_pretrained_2021-10-30_21-51-15_Gfe/denoising_model_hyperparams.json --load_imputation_branch experiments/SHL_trj_pretrained_2021-10-30_21-54-44_HL1/checkpoints/model_best.pth --load_denoising_branch experiments/SHL_feature_pretrained_2021-10-30_21-51-15_Gfe/checkpoints/model_best.pth

#----------------10.30------------------
python src/main.py --output_dir experiments --comment "dual branch finetune for classification" --name SHL_dual_branch_finetuned --records_file Classification_records.xls  --data_class trajectory_with_feature --data_name SHL --val_ratio 0.1 --test_ratio 0.2 --epochs 300 --lr 0.001 --optimizer RAdam --batch_size 550 --pos_encoding learnable --d_model 128 --task dual_branch_classification --change_output --key_metric accuracy --imputation_model_hyperparams experiments/SHL_trj_pretrained_2021-10-28_17-01-13_maQ/imputation_model_hyperparams.json --denoising_model_hyperparams experiments/SHL_feature_pretrained_2021-10-28_16-48-00_cHt/denoising_model_hyperparams.json --load_imputation_branch experiments/SHL_trj_pretrained_2021-10-28_17-01-13_maQ/checkpoints/model_best.pth --load_denoising_branch experiments/SHL_feature_pretrained_2021-10-28_16-48-00_cHt/checkpoints/model_best.pth



#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++GEOLIFE+++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


python src/data_preprocess/trajectory_feature_calculation.py  --trjs_path ./data/geolife_extracted/trjs.npy --labels_path ./data/geolife_extracted/labels.npy --n_class 5 --save_dir ./data/geolife_features/

python src/main.py --output_dir experiments --comment "pretraining through imputation" --name geolife_pretrained --records_file Imputation_records.xls --data_class geolife --val_ratio 0.2 --epochs 40 --lr 0.001 --optimizer RAdam --batch_size 1200 --pos_encoding learnable --d_model 128 --num_workers 16

python src/main.py --output_dir experiments --comment "finetune for classification" --name geolife_finetuned --records_file Classification_records.xls --data_class geolife --val_ratio 0.1 --test_ratio 0.2 --epochs 40 --lr 0.001 --optimizer RAdam --batch_size 1200 --pos_encoding learnable --d_model 128 --load_model experiments/geolife_pretrained_2021-10-08_13-36-50_BHd/checkpoints/model_best.pth --task classification --change_output --key_metric accuracy --num_workers 16


python src/main.py --output_dir experiments --comment "finetune for classification" --name geolife_finetuned --records_file Classification_records.xls --data_class geolife --val_ratio 0.1 --test_ratio 0.2 --epochs 200 --lr 0.001 --optimizer RAdam --batch_size 1200 --pos_encoding learnable --d_model 128 --load_model experiments/geolife_finetuned_2021-10-08_14-19-17_DZ2/checkpoints/model_best.pth --task classification --change_output --key_metric accuracy --num_workers 16


#----------------10.30------------------
python src/data_preprocess/trajectory_feature_calculation.py  --trjs_path ./data/geolife_extracted/trjs.npy --labels_path ./data/geolife_extracted/labels.npy --n_class 5 --save_dir ./data/geolife_features/

python src/main.py --output_dir experiments --comment "pretraining through feat_denoising" --name geolife_feature_pretrained --task denoising --records_file Denoising_records.xls --data_class feature --data_name geolife --val_ratio 0.2 --epochs 200 --lr 0.001 --optimizer RAdam --batch_size 510 --pos_encoding learnable --d_model 128 --num_workers 16

python src/main.py --output_dir experiments --comment "pretraining through trj_imputation" --name geolife_trj_pretrained --task imputation --records_file Imputation_records.xls --data_class trajectory --data_name geolife --val_ratio 0.2 --epochs 200 --lr 0.001 --optimizer RAdam --batch_size 510 --pos_encoding learnable --d_model 128 --normalization per_sample_minmax --num_workers 16

python src/main.py --output_dir experiments --comment "dual branch finetune for classification" --name geolife_dual_branch_finetuned --records_file Classification_records.xls  --data_class trajectory_with_feature --data_name geolife --val_ratio 0.1 --test_ratio 0.2 --epochs 300 --lr 0.001 --optimizer RAdam --batch_size 550 --pos_encoding learnable --d_model 128 --task dual_branch_classification --change_output --key_metric accuracy --imputation_model_hyperparams experiments/geolife_trj_pretrained_2021-10-31_00-29-18_HRj/imputation_model_hyperparams.json --denoising_model_hyperparams experiments/geolife_feature_pretrained_2021-10-31_00-29-09_blk/denoising_model_hyperparams.json --load_imputation_branch experiments/geolife_trj_pretrained_2021-10-31_00-29-18_HRj/checkpoints/model_best.pth --load_denoising_branch experiments/geolife_feature_pretrained_2021-10-31_00-29-09_blk/checkpoints/model_best.pth --num_workers 8

#----------------11.09------------------
python src/main.py --output_dir experiments --comment "dual branch finetune for classification" --name geolife_dual_branch_finetuned --records_file Classification_records.xls  --data_class trajectory_with_feature --data_name geolife --val_ratio 0.1 --test_ratio 0.2 --epochs 500 --lr 0.001 --optimizer RAdam --batch_size 550 --pos_encoding learnable --d_model 128 --task dual_branch_classification --change_output --key_metric accuracy --imputation_model_hyperparams experiments/geolife_trj_pretrained_2021-11-08_23-07-16_Qnn/imputation_model_hyperparams.json --denoising_model_hyperparams experiments/geolife_feature_pretrained_2021-11-08_23-07-01_VSu/denoising_model_hyperparams.json --load_imputation_branch experiments/geolife_trj_pretrained_2021-11-08_23-07-16_Qnn/checkpoints/model_best.pth --load_denoising_branch experiments/geolife_feature_pretrained_2021-11-08_23-07-01_VSu/checkpoints/model_best.pth --num_workers 16
#----------------11.13------------------
python src/main.py --output_dir experiments --comment "pretraining through feat_denoising" --name geolife_feature_pretrained --task denoising --records_file Denoising_records.xls --data_class feature --data_name geolife --val_ratio 0.2 --epochs 100 --lr 0.001 --optimizer RAdam --batch_size 520 --pos_encoding learnable --d_model 128 --num_workers 16

python src/main.py --output_dir experiments --comment "pretraining through trj_imputation" --name geolife_trj_pretrained --task imputation --records_file Imputation_records.xls --data_class trajectory --data_name geolife --val_ratio 0.2 --epochs 100 --lr 0.001 --optimizer RAdam --batch_size 520 --pos_encoding learnable --d_model 128 --normalization per_sample_minmax --num_workers 16

python src/main.py --output_dir experiments --comment "dual branch finetune for classification" --name geolife_dual_branch_finetuned --records_file Classification_records.xls  --data_class trajectory_with_feature --data_name geolife --val_ratio 0.1 --test_ratio 0.2 --epochs 120 --lr 0.001 --optimizer RAdam --batch_size 550 --pos_encoding learnable --d_model 128 --task dual_branch_classification --change_output --key_metric accuracy --imputation_model_hyperparams experiments/geolife_trj_pretrained_2021-11-13_17-18-17_w20/imputation_model_hyperparams.json --denoising_model_hyperparams experiments/geolife_feature_pretrained_2021-11-13_17-17-57_A1t/denoising_model_hyperparams.json --load_imputation_branch experiments/geolife_trj_pretrained_2021-11-13_17-18-17_w20/checkpoints/model_best.pth --load_denoising_branch experiments/geolife_feature_pretrained_2021-11-13_17-17-57_A1t/checkpoints/model_best.pth --num_workers 16


#----------------11.24------------------

python src/main.py --output_dir experiments --comment "pretraining through feat_denoising" --name geolife_feature_pretrained --task denoising --records_file Denoising_records.xls --data_class feature --data_name geolife --val_ratio 0.2 --epochs 200 --lr 0.001 --optimizer RAdam --batch_size 520 --pos_encoding learnable --d_model 128 --num_workers 16

python src/main.py --output_dir experiments --comment "pretraining through trj_imputation" --name geolife_trj_pretrained --task imputation --records_file Imputation_records.xls --data_class trajectory --data_name geolife --val_ratio 0.2 --epochs 200 --lr 0.001 --optimizer RAdam --batch_size 520 --pos_encoding learnable --d_model 128 --normalization per_sample_minmax --num_workers 16

python src/main.py --output_dir experiments --comment "dual branch finetune for classification" --name geolife_dual_branch_finetuned --records_file Classification_records.xls  --data_class trajectory_with_feature --data_name geolife --val_ratio 0.1 --test_ratio 0.2 --epochs 300 --lr 0.001 --optimizer RAdam --batch_size 550 --pos_encoding learnable --d_model 128 --task dual_branch_classification --change_output --key_metric accuracy --imputation_model_hyperparams experiments/geolife_trj_pretrained_2021-11-24_20-10-54_f19/imputation_model_hyperparams.json --denoising_model_hyperparams experiments/geolife_feature_pretrained_2021-11-24_15-40-42_fuW/denoising_model_hyperparams.json --load_imputation_branch experiments/geolife_trj_pretrained_2021-11-24_20-10-54_f19/checkpoints/model_best.pth --load_denoising_branch experiments/geolife_feature_pretrained_2021-11-24_15-40-42_fuW/checkpoints/model_best.pth --num_workers 16

#----------------11.25/26------------------
python src/main.py --output_dir experiments --comment "pretraining through feat_denoising" --name SHL_feature_pretrained --task denoising --records_file Denoising_records.xls --data_class feature --data_name SHL --val_ratio 0.1 --test_ratio 0.2 --epochs 200 --lr 0.001 --optimizer RAdam --batch_size 520 --pos_encoding learnable --d_model 128 --num_workers 16

python src/main.py --output_dir experiments --comment "pretraining through trj_imputation" --name SHL_trj_pretrained --task imputation --records_file Imputation_records.xls --data_class trajectory --data_name SHL --val_ratio 0.1 --test_ratio 0.2 --epochs 200 --lr 0.001 --optimizer RAdam --batch_size 540 --pos_encoding learnable --d_model 128 --normalization per_sample_minmax --num_workers 16

python src/main.py --output_dir experiments --comment "dual branch finetune for classification" --name SHL_dual_branch_finetuned --records_file Classification_records.xls  --data_class trajectory_with_feature --data_name SHL --val_ratio 0.1 --test_ratio 0.2 --epochs 200 --lr 0.001 --optimizer RAdam --batch_size 580 --pos_encoding learnable  --task dual_branch_classification --change_output --key_metric accuracy --imputation_model_hyperparams experiments/SHL_trj_pretrained_2021-11-26_11-00-47_yPB/imputation_model_hyperparams.json --denoising_model_hyperparams experiments/SHL_feature_pretrained_2021-11-26_11-00-40_zjr/denoising_model_hyperparams.json --load_imputation_branch experiments/SHL_trj_pretrained_2021-11-26_11-00-47_yPB/checkpoints/model_best.pth --load_denoising_branch experiments/SHL_feature_pretrained_2021-11-26_11-00-40_zjr/checkpoints/model_best.pth --num_workers 16

python src/main.py --output_dir experiments --comment "dual branch finetune for classification" --name SHL_dual_branch_finetuned --records_file Classification_records.xls  --data_class trajectory_with_feature --data_name SHL --val_ratio 0.1 --test_ratio 0.2 --epochs 200 --lr 0.001 --optimizer RAdam --batch_size 200 --pos_encoding learnable --d_model 128 --task dual_branch_classification  --key_metric accuracy  --num_workers 16 --load_model experiments/SHL_dual_branch_finetuned_2021-11-26_12-16-58_QBR/checkpoints/model_last.pth --imputation_model_hyperparams experiments/SHL_trj_pretrained_2021-11-26_11-00-47_yPB/imputation_model_hyperparams.json --denoising_model_hyperparams experiments/SHL_feature_pretrained_2021-11-26_11-00-40_zjr/denoising_model_hyperparams.json --test_only testset

#----------------11.26------------------
#-----cnn
python src/main.py --output_dir experiments --comment "cnn comparative exp" --name SHL_cnn_comparative_exp --task cnn_classification --records_file cnn_records.xls --data_class feature --data_name SHL --val_ratio 0.1 --test_ratio 0.2 --epochs 200 --lr 0.001 --optimizer RAdam --batch_size 20000  --num_workers 16

python src/main.py --output_dir experiments --comment "cnn comparative exp" --name geolife_cnn_comparative_exp --task cnn_classification --records_file cnn_records.xls --data_class feature --data_name geolife --val_ratio 0.1 --test_ratio 0.2 --epochs 1500 --lr 0.001 --optimizer RAdam --batch_size 16000  --num_workers 16
#---evaluate:
python src/main.py --output_dir experiments --comment "cnn comparative exp" --name geolife_cnn_comparative_exp --records_file cnn_records.xls  --data_class feature --data_name SHL --val_ratio 0.1 --test_ratio 0.2 --lr 0.001 --optimizer RAdam --batch_size 8000 --task cnn_classification  --key_metric accuracy  --num_workers 16 --load_model experiments/SHL_cnn_comparative_exp_2021-11-27_09-37-30_Mgl/checkpoints/model_best.pth  --test_only testset
#-----------dual branch
data_name='SHL'
python src/main.py --output_dir experiments --comment "pretraining through feat_denoising" --name SHL_feature_pretrained --task denoising --records_file Denoising_records.xls --data_class feature --data_name SHL --val_ratio 0.1 --test_ratio 0.2 --epochs 200 --lr 0.001 --optimizer RAdam --batch_size 250 --pos_encoding learnable --d_model 256 --num_workers 16

python src/main.py --output_dir experiments --comment "pretraining through trj_imputation" --name SHL_trj_pretrained --task imputation --records_file Imputation_records.xls --data_class trajectory --data_name SHL --val_ratio 0.1 --test_ratio 0.2 --epochs 200 --lr 0.001 --optimizer RAdam --batch_size 250 --pos_encoding learnable --d_model 256 --num_workers 16

python src/main.py --output_dir experiments --comment "dual branch finetune for classification" --name SHL_dual_branch_finetuned --records_file Classification_records.xls  --data_class trajectory_with_feature --data_name SHL --val_ratio 0.1 --test_ratio 0.2 --epochs 100 --lr 0.001 --optimizer RAdam --batch_size 520 --pos_encoding learnable  --task dual_branch_classification --change_output --key_metric accuracy --imputation_model_hyperparams experiments/SHL_trj_pretrained_2021-11-27_01-47-57_bHZ/imputation_model_hyperparams.json --denoising_model_hyperparams experiments/SHL_feature_pretrained_2021-11-27_01-47-51_ho6/denoising_model_hyperparams.json --load_imputation_branch experiments/SHL_trj_pretrained_2021-11-27_01-47-57_bHZ/checkpoints/model_best.pth --load_denoising_branch experiments/SHL_feature_pretrained_2021-11-27_01-47-51_ho6/checkpoints/model_best.pth --num_workers 16

python src/main.py --output_dir experiments --comment "dual branch finetune for classification" --name SHL_dual_branch_finetuned --records_file Classification_records.xls  --data_class trajectory_with_feature --data_name SHL --val_ratio 0.1 --test_ratio 0.2 --epochs 100 --lr 0.001 --optimizer RAdam --batch_size 200 --pos_encoding learnable --d_model 256 --task dual_branch_classification  --key_metric accuracy  --num_workers 16 --load_model experiments/SHL_dual_branch_finetuned_2021-11-27_02-10-28_tVf/checkpoints/model_best.pth --imputation_model_hyperparams experiments/SHL_trj_pretrained_2021-11-27_01-47-57_bHZ/imputation_model_hyperparams.json --denoising_model_hyperparams experiments/SHL_feature_pretrained_2021-11-27_01-47-51_ho6/denoising_model_hyperparams.json --test_only testset
#-----------ssingle branch
python src/main.py --output_dir experiments --comment "denosing branch finetune for classification" --name SHL_denosing_branch_finetuned --records_file Classification_records.xls  --data_class feature --data_name SHL --val_ratio 0.1 --test_ratio 0.2 --epochs 100 --lr 0.001 --optimizer RAdam --batch_size 270 --pos_encoding learnable  --task denoising_branch_classification --change_output --key_metric accuracy --denoising_model_hyperparams experiments/SHL_feature_pretrained_2021-11-26_22-59-22_wb1/denoising_model_hyperparams.json  --load_denoising_branch experiments/SHL_feature_pretrained_2021-11-26_22-59-22_wb1/checkpoints/model_best.pth --num_workers 16

#-------------11.30
python src/main.py --output_dir experiments --comment "pretraining through feat_denoising" --name SHL_feature_pretrained --task denoising --records_file Denoising_records.xls --data_class feature --data_name SHL --val_ratio 0.1 --test_ratio 0.2 --epochs 200 --lr 0.001 --optimizer RAdam --batch_size 250 --pos_encoding learnable --d_model 128 --num_workers 16

python src/main.py --output_dir experiments --comment "pretraining through trj_imputation" --name SHL_trj_pretrained --task imputation --records_file Imputation_records.xls --data_class trajectory --data_name SHL --val_ratio 0.1 --test_ratio 0.2 --epochs 200 --lr 0.001 --optimizer RAdam --batch_size 250 --pos_encoding learnable --d_model 128 --normalization per_sample_minmax --num_workers 16

python src/main.py --output_dir experiments --comment "dual branch finetune for classification" --name SHL_dual_branch_finetuned --records_file Classification_records.xls  --data_class trajectory_with_feature --data_name SHL --val_ratio 0.1 --test_ratio 0.2 --epochs 300 --lr 0.001 --optimizer RAdam --batch_size 800 --pos_encoding learnable  --task dual_branch_classification --change_output --key_metric accuracy --imputation_model_hyperparams experiments/SHL_trj_pretrained_2021-11-30_18-05-08_TXX/imputation_model_hyperparams.json --denoising_model_hyperparams experiments/SHL_feature_pretrained_2021-11-30_18-05-02_5gO/denoising_model_hyperparams.json --load_imputation_branch experiments/SHL_trj_pretrained_2021-11-30_18-05-08_TXX/checkpoints/model_best.pth --load_denoising_branch experiments/SHL_feature_pretrained_2021-11-30_18-05-02_5gO/checkpoints/model_best.pth --num_workers 16 --freeze

python src/main.py --output_dir experiments --comment "dual branch finetune for classification" --name SHL_dual_branch_finetuned --records_file Classification_records.xls  --data_class trajectory_with_feature --data_name SHL --val_ratio 0.1 --test_ratio 0.2 --epochs 100 --lr 0.001 --optimizer RAdam --batch_size 200 --pos_encoding learnable --d_model 256 --task dual_branch_classification  --key_metric accuracy  --num_workers 16 --load_model experiments/SHL_dual_branch_finetuned_2021-11-30_19-19-01_Sc4/checkpoints/model_best.pth --imputation_model_hyperparams experiments/SHL_trj_pretrained_2021-11-30_18-05-08_TXX/imputation_model_hyperparams.json --denoising_model_hyperparams experiments/SHL_feature_pretrained_2021-11-30_18-05-02_5gO/denoising_model_hyperparams.json --test_only testset


#-----------single branch
python src/main.py --output_dir experiments --comment "pretraining through feat_denoising" --name SHL_feature_pretrained --task denoising --records_file Denoising_records.xls --data_class feature --data_name SHL --val_ratio 0.1 --test_ratio 0.2 --epochs 30 --lr 0.001 --optimizer RAdam --batch_size 520 --pos_encoding learnable --d_model 128 --num_workers 16

python src/main.py --output_dir experiments --comment "denosing branch finetune for classification" --name SHL_denosing_branch_finetuned --records_file Classification_records.xls  --data_class feature --data_name SHL --val_ratio 0.1 --test_ratio 0.2 --epochs 100 --lr 0.001 --optimizer RAdam --batch_size 520 --pos_encoding learnable  --task denoising_branch_classification --change_output --key_metric accuracy --denoising_model_hyperparams experiments/SHL_feature_pretrained_2021-12-01_13-39-43_uVz/denoising_model_hyperparams.json  --load_denoising_branch experiments/SHL_feature_pretrained_2021-12-01_13-39-43_uVz/checkpoints/model_best.pth --num_workers 16

#continue fine tune:
python src/main.py --output_dir experiments --comment "denosing branch finetune for classification" --name SHL_denosing_branch_finetuned --records_file Classification_records.xls  --data_class feature --data_name SHL --val_ratio 0.1 --test_ratio 0.2 --epochs 80 --lr 0.001 --optimizer RAdam --batch_size 520 --pos_encoding learnable  --task denoising_branch_classification  --key_metric accuracy --denoising_model_hyperparams experiments/SHL_feature_pretrained_2021-12-01_09-41-41_DFi/denoising_model_hyperparams.json  --load_model experiments/SHL_denosing_branch_finetuned_2021-12-01_10-19-09_Ofs/checkpoints/model_best.pth --num_workers 16

python src/main.py --output_dir experiments --comment "denosing branch finetune for classification" --name SHL_denosing_branch_finetuned --records_file Classification_records.xls  --data_class feature --data_name SHL --val_ratio 0.1 --test_ratio 0.2 --batch_size 250 --task denoising_branch_classification  --key_metric accuracy --denoising_model_hyperparams experiments/SHL_feature_pretrained_2021-12-01_13-39-43_uVz/denoising_model_hyperparams.json  --load_model experiments/SHL_denosing_branch_finetuned_2021-12-01_13-46-06_8ba/checkpoints/model_best.pth --num_workers 16 --test_only testset

#-----cnn
python src/main.py --output_dir experiments --comment "cnn comparative exp" --name SHL_cnn_comparative_exp --task cnn_classification --records_file cnn_records.xls --data_class feature --data_name SHL --val_ratio 0.1 --test_ratio 0.2 --epochs 200 --lr 0.001 --optimizer RAdam --batch_size 20000  --num_workers 16

python src/main.py --output_dir experiments --comment "cnn comparative exp" --name geolife_cnn_comparative_exp --records_file cnn_records.xls  --data_class feature --data_name SHL --val_ratio 0.1 --test_ratio 0.2 --batch_size 8000 --task cnn_classification  --key_metric accuracy  --num_workers 16 --load_model experiments/SHL_cnn_comparative_exp_2021-12-01_15-20-24_FZ8/checkpoints/model_best.pth  --test_only testset

#--------------12.2

python src/main.py --output_dir experiments --comment "pretraining through feat_denoising" --name geolife_feature_pretrained --task denoising --records_file Denoising_records.xls --data_class feature --data_name geolife --val_ratio 0.1 --test_ratio 0.2 --epochs 150 --lr 0.001 --optimizer RAdam --batch_size 440 --pos_encoding learnable --d_model 64 --num_workers 16 --num_heads 8 --num_layers 4 --input_type mix

python src/main.py --output_dir experiments --comment "denosing branch finetune for classification" --name geolife_denosing_branch_finetuned --records_file Classification_records.xls  --data_class feature --data_name geolife --val_ratio 0.1 --test_ratio 0.2 --epochs 200 --lr 0.001 --optimizer RAdam --batch_size 440 --pos_encoding learnable  --task denoising_branch_classification --change_output --key_metric accuracy --denoising_model_hyperparams experiments/geolife_feature_pretrained_2021-12-02_16-39-58_g6S/denoising_model_hyperparams.json  --load_denoising_branch experiments/geolife_feature_pretrained_2021-12-02_16-39-58_g6S/checkpoints/model_best.pth --num_workers 16 --input_type mix

#continue fine tune:
python src/main.py --output_dir experiments --comment "denosing branch finetune for classification" --name geolife_denosing_branch_finetuned --records_file Classification_records.xls  --data_class feature --data_name geolife --val_ratio 0.1 --test_ratio 0.2 --epochs 200 --lr 0.001 --optimizer RAdam --batch_size 440 --pos_encoding learnable  --task denoising_branch_classification  --key_metric accuracy --denoising_model_hyperparams experiments/geolife_feature_pretrained_2021-12-02_16-39-58_g6S/denoising_model_hyperparams.json  --load_model experiments/geolife_denosing_branch_finetuned_2021-12-02_18-29-01_l8i/checkpoints/model_best.pth --num_workers 16 --input_type mix

python src/main.py --output_dir experiments --comment "denosing branch finetune for classification" --name geolife_denosing_branch_finetuned --records_file Classification_records.xls  --data_class feature --data_name geolife --val_ratio 0.1 --test_ratio 0.2 --batch_size 250 --task denoising_branch_classification  --key_metric accuracy --denoising_model_hyperparams experiments/geolife_feature_pretrained_2021-12-02_16-39-58_g6S/denoising_model_hyperparams.json  --load_model experiments/geolife_denosing_branch_finetuned_2021-12-02_18-29-01_l8i/checkpoints/model_best.pth --num_workers 16 --test_only testset --input_type clean
#--imputation
python src/main.py --output_dir experiments --comment "pretraining through trj_imputation" --name geolife_trj_pretrained --task imputation --records_file Imputation_records.xls --data_class trajectory --data_name geolife --val_ratio 0.1 --test_ratio 0.2 --epochs 150 --lr 0.001 --optimizer RAdam --batch_size 440 --pos_encoding learnable --d_model 64 --num_workers 16 --num_heads 8 --num_layers 4 --input_type mix
#dual fine tune
python src/main.py --output_dir experiments --comment "dual branch finetune for classification" --name geolife_dual_branch_finetuned --records_file Classification_records.xls  --data_class trajectory_with_feature --data_name geolife --val_ratio 0.1 --test_ratio 0.2 --epochs 200 --lr 0.001 --optimizer RAdam --batch_size 210 --pos_encoding learnable  --task dual_branch_classification --change_output --key_metric accuracy --imputation_model_hyperparams experiments/geolife_trj_pretrained_2021-12-02_21-52-08_wtw/imputation_model_hyperparams.json --denoising_model_hyperparams experiments/geolife_feature_pretrained_2021-12-02_16-39-58_g6S/denoising_model_hyperparams.json --load_imputation_branch experiments/geolife_trj_pretrained_2021-12-02_21-52-08_wtw/checkpoints/model_best.pth --load_denoising_branch experiments/geolife_feature_pretrained_2021-12-02_16-39-58_g6S/checkpoints/model_best.pth --num_workers 16 --input_type mix

# continue
python src/main.py --output_dir experiments --comment "denosing branch finetune for classification" --name geolife_denosing_branch_finetuned --records_file Classification_records.xls  --data_class feature --data_name geolife --val_ratio 0.1 --test_ratio 0.2 --epochs 200 --lr 0.001 --optimizer RAdam --batch_size 440 --pos_encoding learnable  --task denoising_branch_classification  --key_metric accuracy --imputation_model_hyperparams experiments/geolife_trj_pretrained_2021-12-02_21-52-08_wtw/imputation_model_hyperparams.json --denoising_model_hyperparams experiments/geolife_feature_pretrained_2021-12-02_16-39-58_g6S/denoising_model_hyperparams.json  --load_model experiments/geolife_dual_branch_finetuned_2021-12-02_22-42-02_qh1/checkpoints/model_best.pth --num_workers 16 --input_type mix

#---cnn
python src/main.py --output_dir experiments --comment "cnn comparative exp" --name geolife_cnn_comparative_exp --task cnn_classification --records_file cnn_records.xls --data_class feature --data_name geolife --val_ratio 0.1 --test_ratio 0.2 --epochs 200 --lr 0.001 --optimizer RAdam --batch_size 20000  --num_workers 16

python src/main.py --output_dir experiments --comment "cnn comparative exp" --name geolife_cnn_comparative_exp --records_file cnn_records.xls  --data_class feature --data_name geolife --val_ratio 0.1 --test_ratio 0.2 --batch_size 8000 --task cnn_classification  --key_metric accuracy  --num_workers 16 --load_model experiments/geolife_cnn_comparative_exp_2021-12-02_12-15-18_RNR/checkpoints/model_best.pth  --test_only testset

#------12.5
#dual fine tune
python src/main.py --output_dir experiments --comment "dual branch finetune for classification" --name geolife_dual_branch_finetuned --records_file Classification_records.xls  --data_class trajectory_with_feature --data_name geolife --val_ratio 0.1 --test_ratio 0.2 --epochs 200 --lr 0.001 --optimizer RAdam --batch_size 210 --pos_encoding learnable  --task dual_branch_classification --change_output --key_metric accuracy --imputation_model_hyperparams experiments/geolife_trj_pretrained_2021-12-02_21-52-08_wtw/imputation_model_hyperparams.json --denoising_model_hyperparams experiments/geolife_feature_pretrained_2021-12-02_16-39-58_g6S/denoising_model_hyperparams.json --load_imputation_branch experiments/geolife_trj_pretrained_2021-12-02_21-52-08_wtw/checkpoints/model_best.pth --load_denoising_branch experiments/geolife_feature_pretrained_2021-12-02_16-39-58_g6S/checkpoints/model_best.pth --num_workers 16 --input_type mix

#test
python src/main.py --output_dir experiments --comment "dual branch finetune for classification" --name geolife_dual_branch_finetuned --records_file Classification_records.xls  --data_class trajectory_with_feature --data_name geolife --val_ratio 0.1 --test_ratio 0.2  --batch_size 150 --pos_encoding learnable  --task dual_branch_classification --key_metric accuracy --imputation_model_hyperparams experiments/geolife_trj_pretrained_2021-12-02_21-52-08_wtw/imputation_model_hyperparams.json --denoising_model_hyperparams experiments/geolife_feature_pretrained_2021-12-02_16-39-58_g6S/denoising_model_hyperparams.json --load_model experiments/geolife_dual_branch_finetuned_2021-12-05_14-33-47_8yP/checkpoints/model_best.pth --num_workers 16 --input_type clean --test_only testset

#seg=128
python src/main.py --output_dir experiments --comment "pretraining through trj_imputation" --name geolife_trj_pretrained --task imputation --records_file Imputation_records.xls --data_class trajectory --data_name geolife --val_ratio 0.1 --test_ratio 0.2 --epochs 100 --lr 0.001 --optimizer RAdam --batch_size 440 --pos_encoding learnable --d_model 64 --num_workers 16 --num_heads 8 --num_layers 4 --input_type mix


python src/main.py --output_dir experiments --comment "pretraining through feat_denoising" --name geolife_feature_pretrained --task denoising --records_file Denoising_records.xls --data_class feature --data_name geolife --val_ratio 0.1 --test_ratio 0.2 --epochs 150 --lr 0.001 --optimizer RAdam --batch_size 440 --pos_encoding learnable --d_model 64 --num_workers 16 --num_heads 8 --num_layers 4 --input_type mix


python src/main.py --output_dir experiments --comment "dual branch finetune for classification" --name geolife_dual_branch_finetuned --records_file Classification_records.xls  --data_class trajectory_with_feature --data_name geolife --val_ratio 0.1 --test_ratio 0.2 --epochs 200 --lr 0.001 --optimizer RAdam --batch_size 440 --pos_encoding learnable  --task dual_branch_classification --change_output --key_metric accuracy --imputation_model_hyperparams experiments/geolife_trj_pretrained_2021-12-05_16-27-47_RMK/imputation_model_hyperparams.json --denoising_model_hyperparams experiments/geolife_feature_pretrained_2021-12-05_16-31-27_Tbe/denoising_model_hyperparams.json --load_imputation_branch experiments/geolife_trj_pretrained_2021-12-05_16-27-47_RMK/checkpoints/model_best.pth --load_denoising_branch experiments/geolife_feature_pretrained_2021-12-05_16-31-27_Tbe/checkpoints/model_best.pth --num_workers 16 --input_type mix

#test
python src/main.py --output_dir experiments --comment "dual branch finetune for classification" --name geolife_dual_branch_finetuned --records_file Classification_records.xls  --data_class trajectory_with_feature --data_name geolife --val_ratio 0.1 --test_ratio 0.2  --batch_size 200 --pos_encoding learnable  --task dual_branch_classification --key_metric accuracy --imputation_model_hyperparams experiments/geolife_trj_pretrained_2021-12-05_16-27-47_RMK/imputation_model_hyperparams.json --denoising_model_hyperparams experiments/geolife_feature_pretrained_2021-12-05_16-31-27_Tbe/denoising_model_hyperparams.json --load_model experiments/geolife_dual_branch_finetuned_2021-12-05_17-40-30_qAx/checkpoints/model_best.pth  --num_workers 16 --input_type mix --test_only testset

#-----12.6
#imputation classfification
python src/main.py --output_dir experiments --comment "imputation branch finetune for classification" --name geolife_imputation_branch_finetuned --records_file Classification_records.xls  --data_class trajectory --data_name geolife --val_ratio 0.1 --test_ratio 0.2 --epochs 200 --lr 0.001 --optimizer RAdam --batch_size 950 --pos_encoding learnable  --task imputation_branch_classification --change_output --key_metric accuracy --imputation_model_hyperparams experiments/geolife_trj_pretrained_2021-12-05_16-27-47_RMK/imputation_model_hyperparams.json  --load_model experiments/geolife_trj_pretrained_2021-12-05_16-27-47_RMK/checkpoints/model_best.pth --num_workers 16 --input_type mix

#denosing classification
python src/main.py --output_dir experiments --comment "denoising branch finetune for classification" --name geolife_denoising_branch_finetuned --records_file Classification_records.xls  --data_class feature --data_name geolife --val_ratio 0.1 --test_ratio 0.2 --epochs 200 --lr 0.001 --optimizer RAdam --batch_size 500 --pos_encoding learnable  --task denoising_branch_classification --change_output --key_metric accuracy --denoising_model_hyperparams experiments/geolife_feature_pretrained_2021-12-05_16-31-27_Tbe/denoising_model_hyperparams.json  --load_model experiments/geolife_feature_pretrained_2021-12-05_16-31-27_Tbe/checkpoints/model_best.pth --num_workers 16 --input_type mix

#test
python src/main.py --output_dir experiments --comment "denoising branch finetune for classification" --name geolife_denoising_branch_finetuned --records_file Classification_records.xls  --data_class feature --data_name geolife --val_ratio 0.1 --test_ratio 0.2  --batch_size 200 --pos_encoding learnable  --task denoising_branch_classification --key_metric accuracy --denoising_model_hyperparams experiments/geolife_feature_pretrained_2021-12-05_16-31-27_Tbe/denoising_model_hyperparams.json  --load_model experiments/geolife_denoising_branch_finetuned_2021-12-06_11-34-22_L1m/checkpoints/model_best.pth  --num_workers 16 --input_type clean --test_only testset

#concat
python src/main.py --output_dir experiments --comment "dual branch finetune for classification" --name geolife_dual_branch_finetuned --records_file Classification_records.xls  --data_class trajectory_with_feature --data_name geolife --val_ratio 0.1 --test_ratio 0.2 --epochs 200 --lr 0.001 --optimizer RAdam --batch_size 440 --pos_encoding learnable  --task dual_branch_classification --change_output --key_metric accuracy --imputation_model_hyperparams experiments/geolife_trj_pretrained_2021-12-05_16-27-47_RMK/imputation_model_hyperparams.json --denoising_model_hyperparams experiments/geolife_feature_pretrained_2021-12-05_16-31-27_Tbe/denoising_model_hyperparams.json --load_imputation_branch experiments/geolife_trj_pretrained_2021-12-05_16-27-47_RMK/checkpoints/model_best.pth --load_denoising_branch experiments/geolife_feature_pretrained_2021-12-05_16-31-27_Tbe/checkpoints/model_best.pth --num_workers 16 --input_type mix

python src/main.py --output_dir experiments --comment "dual branch finetune for classification" --name geolife_dual_branch_finetuned --records_file Classification_records.xls  --data_class trajectory_with_feature --data_name geolife --val_ratio 0.1 --test_ratio 0.2  --batch_size 200 --pos_encoding learnable  --task dual_branch_classification --key_metric accuracy --imputation_model_hyperparams experiments/geolife_trj_pretrained_2021-12-05_16-27-47_RMK/imputation_model_hyperparams.json --denoising_model_hyperparams experiments/geolife_feature_pretrained_2021-12-05_16-31-27_Tbe/denoising_model_hyperparams.json --load_model experiments/geolife_dual_branch_finetuned_2021-12-05_17-40-30_qAx/checkpoints/model_best.pth  --num_workers 16 --input_type clean --test_only testset


#fix bug
python src/main.py --output_dir experiments --comment "dual branch finetune for classification" --name geolife_dual_branch_finetuned --records_file Classification_records.xls  --data_class trajectory_with_feature --data_name geolife --val_ratio 0.1 --test_ratio 0.2 --epochs 200 --lr 0.001 --optimizer RAdam --batch_size 500 --pos_encoding learnable  --task dual_branch_classification --change_output --key_metric accuracy --imputation_model_hyperparams experiments/geolife_trj_pretrained_2021-12-06_18-18-57_4E9/imputation_model_hyperparams.json --denoising_model_hyperparams experiments/geolife_feature_pretrained_2021-12-05_16-31-27_Tbe/denoising_model_hyperparams.json --load_imputation_branch experiments/geolife_trj_pretrained_2021-12-06_18-18-57_4E9/checkpoints/model_best.pth --load_denoising_branch experiments/geolife_feature_pretrained_2021-12-05_16-31-27_Tbe/checkpoints/model_best.pth --num_workers 16 --input_type mix

python src/main.py --output_dir experiments --comment "dual branch finetune for classification" --name geolife_dual_branch_finetuned --records_file Classification_records.xls  --data_class trajectory_with_feature --data_name geolife --val_ratio 0.1 --test_ratio 0.2  --batch_size 200 --pos_encoding learnable  --task dual_branch_classification --imputation_model_hyperparams experiments/geolife_trj_pretrained_2021-12-06_18-18-57_4E9/imputation_model_hyperparams.json --denoising_model_hyperparams experiments/geolife_feature_pretrained_2021-12-05_16-31-27_Tbe/denoising_model_hyperparams.json --load_model experiments/geolife_dual_branch_finetuned_2021-12-06_19-20-49_S6J/checkpoints/model_best.pth --num_workers 16 --input_type clean --test_only testset


#SHL

python src/main.py --output_dir experiments --comment "pretraining through trj_imputation" --name SHL_trj_pretrained --task imputation --records_file Imputation_records.xls --data_class trajectory --data_name SHL --val_ratio 0.1 --test_ratio 0.2 --epochs 150 --lr 0.001 --optimizer RAdam --batch_size 440 --pos_encoding learnable --d_model 64 --num_workers 16 --num_heads 8 --num_layers 4 --input_type mix


python src/main.py --output_dir experiments --comment "pretraining through feat_denoising" --name SHL_feature_pretrained --task denoising --records_file Denoising_records.xls --data_class feature --data_name SHL --val_ratio 0.1 --test_ratio 0.2 --epochs 150 --lr 0.001 --optimizer RAdam --batch_size 900 --pos_encoding learnable --d_model 64 --num_workers 16 --num_heads 8 --num_layers 4 --input_type mix

python src/main.py --output_dir experiments --comment "dual branch finetune for classification" --name SHL_dual_branch_finetuned --records_file Classification_records.xls  --data_class trajectory_with_feature --data_name SHL --val_ratio 0.1 --test_ratio 0.2 --epochs 20000 --lr 0.001 --optimizer RAdam --batch_size 450 --pos_encoding learnable  --task dual_branch_classification --change_output --key_metric accuracy --imputation_model_hyperparams experiments/SHL_trj_pretrained_2021-12-06_21-51-57_vkv/imputation_model_hyperparams.json --denoising_model_hyperparams experiments/SHL_feature_pretrained_2021-12-06_22-00-15_5aT/denoising_model_hyperparams.json --load_imputation_branch experiments/SHL_trj_pretrained_2021-12-06_21-51-57_vkv/checkpoints/model_best.pth --load_denoising_branch experiments/SHL_feature_pretrained_2021-12-06_22-00-15_5aT/checkpoints/model_best.pth --num_workers 16 --input_type mix


python src/main.py --output_dir experiments --comment "dual branch finetune for classification" --name SHL_dual_branch_finetuned --records_file Classification_records.xls  --data_class trajectory_with_feature --data_name SHL --val_ratio 0.1 --test_ratio 0.2  --batch_size 200 --pos_encoding learnable  --task dual_branch_classification --imputation_model_hyperparams experiments/SHL_trj_pretrained_2021-12-06_21-51-57_vkv/imputation_model_hyperparams.json --denoising_model_hyperparams experiments/SHL_feature_pretrained_2021-12-06_22-00-15_5aT/denoising_model_hyperparams.json --load_model experiments/SHL_dual_branch_finetuned_2021-12-06_23-03-46_djr/checkpoints/model_best.pth --num_workers 16 --input_type clean --test_only testset

python src/main.py --output_dir experiments --comment "denosing branch finetune for classification" --name SHL_denosing_branch_finetuned --records_file Classification_records.xls  --data_class feature --data_name SHL --val_ratio 0.1 --test_ratio 0.2 --batch_size 480 --task denoising_branch_classification  --epochs 200 --lr 0.001 --optimizer RAdam --change_output --key_metric accuracy --pos_encoding learnable --denoising_model_hyperparams experiments/SHL_feature_pretrained_2021-12-06_22-00-15_5aT/denoising_model_hyperparams.json  --load_model experiments/SHL_dual_branch_finetuned_2021-12-06_22-10-24_lhZ/checkpoints/model_best.pth --num_workers 16 --input_type mix


python src/main.py --output_dir experiments --comment "denosing branch finetune for classification" --name SHL_denosing_branch_finetuned --records_file Classification_records.xls  --data_class feature --data_name SHL --val_ratio 0.1 --test_ratio 0.2 --batch_size 300 --task denoising_branch_classification  --pos_encoding learnable --denoising_model_hyperparams experiments/SHL_feature_pretrained_2021-12-06_22-00-15_5aT/denoising_model_hyperparams.json  --load_model experiments/SHL_denosing_branch_finetuned_2021-12-06_22-50-05_P03/checkpoints/model_best.pth --num_workers 16 --input_type clean --test_only testset


#-----12.7
#denoising imputation
python src/main.py --output_dir experiments --comment "pretraining through feat_denoising_imputation" --name SHL_feature_pretrained --task denoising_imputation --records_file Denoising_imputation_records.xls --data_class feature --data_name SHL --val_ratio 0.1 --test_ratio 0.2 --epochs 200 --lr 0.001 --optimizer RAdam --batch_size 900 --pos_encoding learnable --d_model 64 --num_workers 16 --num_heads 8 --num_layers 4 --input_type mix

python src/main.py --output_dir experiments --comment "finetune for classification" --name SHL_feature_finetune --task denoising_imputation_classification --records_file Classification_records.xls --data_class feature --data_name SHL --val_ratio 0.1 --test_ratio 0.2 --epochs 200 --lr 0.001 --optimizer RAdam --batch_size 900 --pos_encoding learnable --d_model 64 --num_workers 16 --num_heads 8 --num_layers 4 --input_type mix --change_output --key_metric accuracy --denoising_imputation_model_hyperparams experiments/SHL_feature_pretrained_2021-12-07_09-38-37_B66/denoising_imputation_model_hyperparams.json --load_model experiments/SHL_feature_pretrained_2021-12-07_09-38-37_B66/checkpoints/model_best.pth

python src/main.py --output_dir experiments --comment "finetune for classification" --name SHL_feature_finetune_classification --task denoising_imputation_classification --records_file Classification_records.xls --data_class feature --data_name SHL --val_ratio 0.1 --test_ratio 0.2 --batch_size 300 --pos_encoding learnable --d_model 64 --num_workers 16 --num_heads 8 --num_layers 4 --input_type clean --denoising_imputation_model_hyperparams experiments/SHL_feature_pretrained_2021-12-07_09-38-37_B66/denoising_imputation_model_hyperparams.json --load_model experiments/SHL_feature_finetune_2021-12-07_09-58-19_tOC/checkpoints/model_best.pth --test_only testset

#feat denoising imputation, trj imputation
python src/main.py --output_dir experiments --comment "finetune for classification" --name SHL_dual_branch_finetune --task dual_branch_classification --records_file Classification_records.xls --data_class trajectory_with_feature --data_name SHL --val_ratio 0.1 --test_ratio 0.2 --epochs 200 --lr 0.001 --optimizer RAdam --batch_size 500 --pos_encoding learnable --d_model 64 --num_workers 16 --num_heads 8 --num_layers 4 --input_type mix --change_output --key_metric accuracy --denoising_model_hyperparams experiments/SHL_feature_pretrained_2021-12-07_09-38-37_B66/denoising_imputation_model_hyperparams.json --imputation_model_hyperparams experiments/SHL_trj_pretrained_2021-12-06_21-51-57_vkv/imputation_model_hyperparams.json --load_denoising_branch experiments/SHL_feature_pretrained_2021-12-07_09-38-37_B66/checkpoints/model_best.pth --load_imputation_branch experiments/SHL_trj_pretrained_2021-12-06_21-51-57_vkv/checkpoints/model_best.pth


python src/main.py --output_dir experiments --comment "finetune for classification" --name SHL_dual_branch_finetune --task dual_branch_classification --records_file Classification_records.xls --data_class trajectory_with_feature --data_name SHL --val_ratio 0.1 --test_ratio 0.2 --batch_size 300 --pos_encoding learnable --d_model 64 --num_workers 16 --num_heads 8 --num_layers 4 --input_type clean --denoising_model_hyperparams experiments/SHL_feature_pretrained_2021-12-07_09-38-37_B66/denoising_imputation_model_hyperparams.json --imputation_model_hyperparams experiments/SHL_trj_pretrained_2021-12-06_21-51-57_vkv/imputation_model_hyperparams.json --load_model experiments/SHL_dual_branch_finetune_2021-12-07_10-25-00_e8D/checkpoints/model_best.pth --test_only testset


#12.10
python src/main.py --output_dir experiments --comment "pretraining through feat_denoising_imputation" --name SHL_feature_pretrained --task denoising_imputation --records_file Denoising_imputation_records.xls --data_class feature --data_name SHL --val_ratio 0.1 --test_ratio 0.2 --epochs 150 --lr 0.001 --optimizer RAdam --batch_size 800 --num_workers 16 --pos_encoding learnable --d_model 64 --num_heads 8 --num_layers 4 --dim_feedforward 512 --input_type mix

python src/main.py --output_dir experiments --comment "pretraining through trj_imputation" --name SHL_trj_pretrained --task denoising_imputation --records_file Denoising_imputation_records.xls --data_class trajectory --data_name SHL --val_ratio 0.1 --test_ratio 0.2 --epochs 80 --lr 0.001 --optimizer RAdam --batch_size 820 --pos_encoding learnable --num_workers 16 --d_model 64  --num_heads 8 --num_layers 4 --dim_feedforward 512 --input_type mix


python src/main.py --output_dir experiments --comment "finetune for classification" --name SHL_dual_branch_finetune --task dual_branch_classification --records_file Classification_records.xls --data_class trajectory_with_feature --data_name SHL --val_ratio 0.1 --test_ratio 0.2 --epochs 7000 --lr 0.001 --optimizer RAdam --batch_size 460 --pos_encoding learnable --num_workers 16 --input_type mix --change_output --key_metric accuracy --denoising_model_hyperparams experiments/SHL_feature_pretrained_2021-12-10_20-25-16_zXg/denoising_imputation_model_hyperparams.json --imputation_model_hyperparams experiments/SHL_trj_pretrained_2021-12-06_21-51-57_vkv/imputation_model_hyperparams.json --load_denoising_branch experiments/SHL_feature_pretrained_2021-12-10_20-25-16_zXg/checkpoints/model_best.pth --load_imputation_branch experiments/SHL_trj_pretrained_2021-12-06_21-51-57_vkv/checkpoints/model_best.pth

#single
python src/main.py --output_dir experiments --comment "finetune for classification" --name SHL_feature_finetune --task denoising_imputation_classification --records_file Classification_records.xls --data_class feature --data_name SHL --val_ratio 0.1 --test_ratio 0.2 --epochs 200 --lr 0.001 --optimizer RAdam --batch_size 900 --pos_encoding learnable --d_model 64 --num_workers 16 --num_heads 8 --num_layers 4 --input_type mix --change_output --key_metric accuracy --denoising_imputation_model_hyperparams experiments/SHL_feature_pretrained_2021-12-10_20-25-16_zXg/denoising_imputation_model_hyperparams.json --load_model experiments/SHL_feature_finetune_2021-12-11_00-26-32_cmB/checkpoints/model_best.pth

python src/main.py --output_dir experiments --comment "finetune for classification" --name SHL_feature_finetune --task denoising_imputation_classification --records_file Classification_records.xls --data_class feature --data_name SHL --val_ratio 0.1 --test_ratio 0.2 --batch_size 300  --num_workers 16 --input_type noise --denoising_imputation_model_hyperparams experiments/SHL_feature_pretrained_2021-12-10_20-25-16_zXg/denoising_imputation_model_hyperparams.json --load_model experiments/SHL_feature_finetune_2021-12-11_00-37-58_QYk/checkpoints/model_best.pth  --test_only testset


#no pre
python src/main.py --output_dir experiments --comment "finetune for classification" --name SHL_dual_branch_finetune --task dual_branch_classification --records_file Classification_records.xls --data_class trajectory_with_feature --data_name SHL --val_ratio 0.1 --test_ratio 0.2 --epochs 200 --lr 0.001 --optimizer RAdam --batch_size 400 --pos_encoding learnable --num_workers 16 --input_type mix --change_output --key_metric accuracy --denoising_model_hyperparams experiments/SHL_feature_pretrained_2021-12-10_20-25-16_zXg/denoising_imputation_model_hyperparams.json --imputation_model_hyperparams experiments/SHL_trj_pretrained_2021-12-06_21-51-57_vkv/imputation_model_hyperparams.json

python src/main.py --output_dir experiments --comment "finetune for classification" --name SHL_dual_branch_finetune --task dual_branch_classification --records_file Classification_records.xls --data_class trajectory_with_feature --data_name SHL --val_ratio 0.1 --test_ratio 0.2 --batch_size 400 --num_workers 16 --input_type clean --denoising_model_hyperparams experiments/SHL_feature_pretrained_2021-12-10_20-25-16_zXg/denoising_imputation_model_hyperparams.json --imputation_model_hyperparams experiments/SHL_trj_pretrained_2021-12-06_21-51-57_vkv/imputation_model_hyperparams.json --load_model experiments/SHL_dual_branch_finetune_2021-12-11_00-49-56_HX4/checkpoints/model_best.pth  --test_only testset

#cnn
python src/main.py --output_dir experiments --comment "cnn comparative exp" --name SHL_cnn_comparative_exp --task cnn_classification --records_file cnn_records.xls --data_class feature --data_name SHL --val_ratio 0.1 --test_ratio 0.2 --epochs 200 --lr 0.001 --optimizer RAdam --batch_size 20000  --num_workers 16 --activation relu --input_type mix

python src/main.py --output_dir experiments --comment "cnn comparative exp" --name SHL_cnn_comparative_exp --records_file cnn_records.xls  --data_class feature --data_name SHL --val_ratio 0.1 --test_ratio 0.2 --batch_size 8000 --task cnn_classification  --key_metric accuracy  --num_workers 16 --load_model experiments/SHL_cnn_comparative_exp_2021-12-11_08-36-20_agf/checkpoints/model_best.pth  --test_only testset --input_type clean


#test
python src/main.py --output_dir experiments --comment "finetune for classification" --name SHL_dual_branch_finetune --task dual_branch_classification --records_file Classification_records.xls --data_class trajectory_with_feature --data_name SHL --val_ratio 0.1 --test_ratio 0.2 --lr 0.001 --optimizer RAdam --batch_size 350 --num_workers 16 --input_type noise --denoising_model_hyperparams experiments/SHL_feature_pretrained_2021-12-10_20-25-16_zXg/denoising_imputation_model_hyperparams.json --imputation_model_hyperparams experiments/SHL_trj_pretrained_2021-12-06_21-51-57_vkv/imputation_model_hyperparams.json --load_model experiments/SHL_dual_branch_finetune_2021-12-10_20-31-52_oeB/checkpoints/model_best.pth --test_only testset


